
#ifndef __VRTULETREE_IOCTLS_H_
#define __VRTULETREE_IOCTLS_H_

#include <ntifs.h>



#define IOCTL_VTREE_SNAPSHOT_GET             CTL_CODE(FILE_DEVICE_UNKNOWN, 0x02, METHOD_BUFFERED, FILE_WRITE_ACCESS)


#define VTREE_SNAPSHOT_DEVICE_ID							0x1
#define VTREE_SNAPSHOT_FAST_IO_DISPATCH  					0x2
#define VTREE_SNAPSHOT_DEVNODE_TREE  						0x4

typedef struct _VRTULETREE_KERNEL_SNAPSHOT_INPUT {
	ULONG SnapshotFlags;
} VRTULETREE_KERNEL_SNAPSHOT_INPUT, *PVRTULETREE_KERNEL_SNAPSHOT_INPUT;



#endif
