
#ifndef __VRTULETREE_IOCTLS_H_
#define __VRTULETREE_IOCTLS_H_

#include <ntifs.h>



#define IOCTL_VTREE_SNAPSHOT_GET             CTL_CODE(FILE_DEVICE_UNKNOWN, 0x02, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_VTREE_SPECIAL_VALUS_GET		 CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03, METHOD_BUFFERED, FILE_WRITE_ACCESS)


#define VTREE_SNAPSHOT_DEVICE_ID							0x1
#define VTREE_SNAPSHOT_FAST_IO_DISPATCH  					0x2
#define VTREE_SNAPSHOT_DEVNODE_TREE  						0x4

typedef struct _VRTULETREE_KERNEL_SNAPSHOT_INPUT {
	ULONG SnapshotFlags;
} VRTULETREE_KERNEL_SNAPSHOT_INPUT, *PVRTULETREE_KERNEL_SNAPSHOT_INPUT;

typedef struct _IOCTL_VTREE_SPECIAL_VALUS_GET_OUTPUT {
	DRIVER_DISPATCH *IopInvalidDeviceRequest;
	FAST_IO_ACQUIRE_FILE *FsRtlAcquireFileExclusive;
	FAST_IO_READ *FsRtlCopyRead;
	FAST_IO_WRITE *FsRtlCopyWrite;
	FAST_IO_MDL_READ *FsRtlMdlRead;
	FAST_IO_MDL_READ_COMPLETE *FsRtlMdlReadComplete;
	FAST_IO_PREPARE_MDL_WRITE *FsRtlPrepareMdlWrite;
	FAST_IO_MDL_WRITE_COMPLETE *FsRtlMdlWriteComplete;
	FAST_IO_RELEASE_FILE *FsRtlReleaseFile;
} IOCTL_VTREE_SPECIAL_VALUS_GET_OUTPUT, *PIOCTL_VTREE_SPECIAL_VALUS_GET_OUTPUT;


#endif
